name: WarPlugin
main: me.keycatchupwhy.warplugin.Main
version: 1.0
api-version: 1.12
commands:
   makeTeam:
      description: Make your own team
      usage: /maketeam
   joinTeam:
      description: Join other team
      usage: /jointeam
   listTeam:
      description: List all teams
      usage: /listteam
   checkTeam:
      description: List all teams
      usage: /listteam