name: WarPlugin
main: me.keycatchupwhy.warplugin.Main
version: 1.0
api-version: 1.16
softdepend: ['Multiverse-Core']
commands:
   makeTeam:
      description: Make your own team
      usage: /maketeam
   joinTeam:
      description: Join other team
      usage: /jointeam
   listTeam:
      description: List all teams
      usage: /listteam
   checkTeam:
      description: Check what team you are in
      usage: /checkTeam
   kickTeam:
      description: Kick player
      usage: /kickTeam <player>
   warmanager:
      description: Show a war manager ui
      usage: /warmanager