name: WarPlugin
main: me.keycatchupwhy.warplugin.Main
version: 1.0
api-version: 1.16
commands:
   makeTeam:
      description: Make your own team
      usage: /maketeam
   joinTeam:
      description: Join other team
      usage: /jointeam
   listTeam:
      description: List all teams
      usage: /listteam
   checkTeam:
      description: List all teams
      usage: /listteam
   warmanager:
      description: Show a war manager ui
      usage: /warmanager
   changespeed:
      description: Changes the speed of war
      usage: /changespeed